# Generated by Django 3.0.7 on 2020-06-26 03:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_string', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Accept Encoding String')),
            ],
            options={
                'verbose_name': 'Accept Encoding',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lookup_time', models.FloatField(blank=True, default=0, null=True, verbose_name='DNS Lookup Time')),
                ('ssl_time', models.FloatField(blank=True, default=0, null=True, verbose_name='SSL Time')),
                ('connect_time', models.FloatField(blank=True, default=0, null=True, verbose_name='Connect Time')),
                ('response_time', models.FloatField(default=0, verbose_name='Response Time')),
                ('log_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(verbose_name='HTTP Status Code')),
                ('protocol', models.CharField(choices=[('0', 'Unknown'), ('9', 'HTTP/1.0'), ('1', 'HTTP/1.0'), ('2', 'HTTP/1.1'), ('3', 'HTTP/2')], default='0', max_length=1)),
                ('method', models.CharField(choices=[('0', 'UNKNOWN'), ('1', 'GET'), ('2', 'HEAD'), ('3', 'POST'), ('4', 'PUT'), ('5', 'DELETE'), ('6', 'CONNECT'), ('7', 'OPTIONS'), ('8', 'TRACE'), ('9', 'PATCH')], default='1', max_length=1)),
                ('ajax', models.BooleanField(default=False, verbose_name='AJAX Request')),
                ('preview', models.BooleanField(default=False, verbose_name='Preview Request')),
                ('prefetch', models.BooleanField(default=False, verbose_name='Prefetch Request')),
                ('request_content_length', models.PositiveIntegerField(blank=True, null=True)),
                ('response_content_length', models.PositiveIntegerField(blank=True, null=True)),
                ('compress', models.CharField(choices=[('0', 'None'), ('1', 'gzip'), ('2', 'SDCH'), ('3', 'Brotli'), ('4', 'deflate')], default='0', max_length=1)),
                ('cached', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Accesses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(db_index=True, max_length=254)),
                ('major_version', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('minor_version', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('patch', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_2', models.CharField(max_length=2, unique=True)),
                ('alpha_3', models.CharField(max_length=3, unique=True)),
                ('numeric', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510)),
                ('official_name', models.CharField(blank=True, max_length=500, null=True)),
                ('common_name', models.CharField(blank=True, max_length=140, null=True)),
                ('UN_formal_name', models.CharField(blank=True, max_length=160, null=True)),
                ('UN_short_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Country Lang',
                'verbose_name_plural': 'Countries Lang',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, db_index=True, max_length=254)),
                ('brand', models.CharField(db_index=True, max_length=254, null=True)),
                ('model', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('mobile', models.BooleanField(default=False)),
                ('pc', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('touch', models.BooleanField(default=False)),
                ('bot', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Domain Name')),
                ('bot', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Domain Name',
            },
        ),
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_string', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Request Encoding String')),
            ],
            options={
                'verbose_name': 'Request Encoding',
            },
        ),
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Host')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Host Name',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP Address')),
                ('bot', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addresses',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, max_length=30, null=True)),
                ('extension', models.CharField(blank=True, max_length=30, null=True)),
                ('private_use', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LangLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_3', models.CharField(max_length=3, unique=True)),
                ('iso_639_1', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('iso_639_2b', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('iso_639_2t', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('scope', models.CharField(choices=[('I', 'Individual'), ('M', 'Macrolanguage'), ('S', 'Special')], default='I', max_length=1)),
                ('type', models.CharField(choices=[('A', 'Ancient'), ('C', 'Constructed'), ('E', 'Exctinct'), ('H', 'Historical'), ('L', 'Living'), ('S', 'Special')], default='L', max_length=1)),
            ],
            options={
                'ordering': ['iso_639_3'],
            },
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_string', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Language String')),
            ],
            options={
                'verbose_name': 'Language Encoding',
            },
        ),
        migrations.CreateModel(
            name='LanguageLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_name', models.CharField(max_length=150)),
                ('inverted_name', models.CharField(max_length=150)),
                ('ref_name', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['print_name'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocaleLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MacroLanguageMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('R', 'Retired')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MIME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type_string', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='MIME Type String')),
            ],
            options={
                'verbose_name': 'MIME Type',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(db_index=True, max_length=254)),
                ('major_version', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('minor_version', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('patch', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('minor_patch', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Operating System',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_path', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Search Path String')),
            ],
            options={
                'verbose_name': 'Search Path',
            },
        ),
        migrations.CreateModel(
            name='QueryString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Query String')),
            ],
            options={
                'verbose_name': 'Query String',
            },
        ),
        migrations.CreateModel(
            name='RetiredLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_3', models.CharField(max_length=3, unique=True)),
                ('ref_name', models.CharField(max_length=150)),
                ('reason', models.CharField(choices=[('C', 'Change'), ('D', 'Duplicate'), ('N', 'Nonexistent'), ('S', 'Split'), ('M', 'Merge')], default='C', max_length=1)),
                ('change_to', models.CharField(blank=True, max_length=3, null=True)),
                ('ret_remedy', models.CharField(blank=True, max_length=300, null=True)),
                ('effective_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['iso_639_3'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_15294', models.CharField(max_length=4, unique=True)),
                ('code_number', models.CharField(max_length=3, unique=True)),
                ('unicode_alias', models.CharField(max_length=75)),
                ('unicode_version', models.CharField(max_length=4)),
                ('version_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True)),
                ('expire_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('bot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Session Log',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_subdivisions', to='mozumder.Country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='mozumder.Subdivision')),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_string', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='User Agent String')),
                ('bot', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('browser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozumder.Browser', verbose_name='Browser')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozumder.Device', verbose_name='Device')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozumder.OS', verbose_name='OS')),
            ],
            options={
                'verbose_name': 'User Agent',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=510, unique=True)),
                ('scheme', models.BooleanField(default=True)),
                ('port', models.SmallIntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.HostName')),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.URL')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.Path')),
                ('query_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.QueryString')),
            ],
            options={
                'verbose_name': 'URL',
            },
        ),
        migrations.CreateModel(
            name='SubdivisionTypeLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_type_langs', to='mozumder.Lang')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_types', to='mozumder.SubdivisionType')),
            ],
        ),
        migrations.CreateModel(
            name='SubdivisionLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_langs', to='mozumder.Lang')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_names', to='mozumder.Subdivision')),
            ],
        ),
        migrations.AddField(
            model_name='subdivision',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='mozumder.SubdivisionType'),
        ),
        migrations.CreateModel(
            name='ScriptLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_langs', to='mozumder.Lang')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='mozumder.Script')),
            ],
        ),
        migrations.AddConstraint(
            model_name='os',
            constraint=models.UniqueConstraint(fields=('family', 'major_version', 'minor_version', 'patch', 'minor_patch'), name='os_unique'),
        ),
        migrations.AddField(
            model_name='macrolanguagemapping',
            name='individual_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuallangs', to='mozumder.Language'),
        ),
        migrations.AddField(
            model_name='macrolanguagemapping',
            name='macrolanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macrolangs', to='mozumder.Language'),
        ),
        migrations.AddField(
            model_name='macrolanguagemapping',
            name='retired_individual_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macrolanguages', to='mozumder.RetiredLanguage'),
        ),
        migrations.AddField(
            model_name='localelang',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locale_langs', to='mozumder.Lang'),
        ),
        migrations.AddField(
            model_name='localelang',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='mozumder.Locale'),
        ),
        migrations.AddField(
            model_name='locale',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='mozumder.Country'),
        ),
        migrations.AddField(
            model_name='locale',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='mozumder.Language'),
        ),
        migrations.AddField(
            model_name='locale',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='mozumder.Script'),
        ),
        migrations.AddField(
            model_name='languagelang',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_langs', to='mozumder.Lang'),
        ),
        migrations.AddField(
            model_name='languagelang',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_codes', to='mozumder.Language'),
        ),
        migrations.AddField(
            model_name='langlang',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='mozumder.Lang'),
        ),
        migrations.AddField(
            model_name='langlang',
            name='namedlang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namedlangs', to='mozumder.Lang'),
        ),
        migrations.AddField(
            model_name='lang',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='mozumder.Country'),
        ),
        migrations.AddField(
            model_name='lang',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='mozumder.Language'),
        ),
        migrations.AddField(
            model_name='lang',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='mozumder.Script'),
        ),
        migrations.AddField(
            model_name='ip',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.HostName', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='hostname',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.Domain', verbose_name='Domain'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('brand', 'family', 'model'), name='device_unique'),
        ),
        migrations.AddField(
            model_name='countrylang',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_names', to='mozumder.Country'),
        ),
        migrations.AddField(
            model_name='countrylang',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_langs', to='mozumder.Lang'),
        ),
        migrations.AddConstraint(
            model_name='browser',
            constraint=models.UniqueConstraint(fields=('family', 'major_version', 'minor_version', 'patch'), name='browser_unique'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='accept_encoding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.Encoding'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='accept_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.LanguageCode'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='accept_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.Accept'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozumder.IP', verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='referer_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesslog_referer_url', to='mozumder.URL', verbose_name='Referer'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='request_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesslog_request_content_type', to='mozumder.MIME'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='request_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesslog_request_url', to='mozumder.URL', verbose_name='Request URL'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='response_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesslog_response_content_type', to='mozumder.MIME'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='session_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.SessionLog'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mozumder.UserAgent'),
        ),
        migrations.AddConstraint(
            model_name='subdivisiontypelang',
            constraint=models.UniqueConstraint(fields=('type', 'lang'), name='subdivisiontypelang_unique'),
        ),
        migrations.AddConstraint(
            model_name='subdivisionlang',
            constraint=models.UniqueConstraint(fields=('subdivision', 'lang'), name='subdivisionlang_unique'),
        ),
        migrations.AddConstraint(
            model_name='subdivision',
            constraint=models.UniqueConstraint(fields=('code', 'country'), name='subdivision_unique'),
        ),
        migrations.AddConstraint(
            model_name='scriptlang',
            constraint=models.UniqueConstraint(fields=('script', 'lang'), name='scriptlang_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='macrolanguagemapping',
            constraint=models.UniqueConstraint(fields=('macrolanguage', 'individual_language'), name='individualmacrolanguage_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='macrolanguagemapping',
            constraint=models.UniqueConstraint(fields=('macrolanguage', 'retired_individual_language'), name='retiredindividualmacrolanguage_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='localelang',
            constraint=models.UniqueConstraint(fields=('locale', 'lang'), name='localelang_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='locale',
            constraint=models.UniqueConstraint(fields=('language', 'script', 'country'), name='locale_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='languagelang',
            constraint=models.UniqueConstraint(fields=('language', 'lang', 'print_name'), name='languagelang_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='langlang',
            constraint=models.UniqueConstraint(fields=('namedlang', 'lang'), name='langlang_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='lang',
            constraint=models.UniqueConstraint(fields=('language', 'script', 'country', 'variant', 'extension', 'private_use'), name='lang_uniquetogether'),
        ),
        migrations.AddConstraint(
            model_name='countrylang',
            constraint=models.UniqueConstraint(fields=('country', 'lang'), name='countrylang_unique'),
        ),
    ]
